#!/opt/homebrew/bin/node

// Returns the paragraphs from a Wikipedia link, stripped of reference numbers.

let urllib = require("urllib");
let url = process.argv[2];

const jsdom = require("jsdom");
const { JSDOM } = jsdom;

if(!url) {
  console.log("Usage: wikp <url>");
} else {
  urllib.request(url, { followRedirect: true }, function(error, data, response) {
    let body = data.toString();
    // Simulate a Document Object Model.
    let { document } = (new JSDOM(body)).window;
  
    // Grab all the paragraphs and references. 
    let paragraphs = document.querySelectorAll("p");
    let references = document.querySelectorAll(".reference");
  
    // Remove any reference.
    references.forEach(function(reference) {
      reference.remove();
    });
    
    paragraphs.forEach(function(paragraph) {
      console.log(paragraph.textContent);
    });
  });
}


